In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
import pickle
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = pickle.load(open("X.pickle","rb"))
y = pickle.load(open("y.pickle","rb"))

X = np.array(X).reshape(-1,50,50)
X_train= X[:-10]
X_train=X_train/255.0

y_train=np.array(y[:-10]).reshape(-1,1)

X_train[-3:]

array([[[0.76862745, 0.77254902, 0.54901961, ..., 0.65882353,
         0.3372549 , 0.23529412],
        [0.25490196, 0.2745098 , 0.39215686, ..., 0.82745098,
         0.80784314, 0.78431373],
        [0.79215686, 0.81568627, 0.43921569, ..., 0.76470588,
         0.81568627, 0.78823529],
        ...,
        [0.18431373, 0.18431373, 0.17254902, ..., 0.17647059,
         0.32941176, 0.17647059],
        [0.18431373, 0.17647059, 0.16470588, ..., 0.14117647,
         0.31372549, 0.28627451],
        [0.19215686, 0.17647059, 0.16862745, ..., 0.30196078,
         0.23529412, 0.25490196]],

       [[0.81568627, 0.8       , 0.82745098, ..., 0.81568627,
         0.75294118, 0.56862745],
        [0.80784314, 0.80784314, 0.78431373, ..., 0.81176471,
         0.83529412, 0.72156863],
        [0.8       , 0.79215686, 0.77254902, ..., 0.85882353,
         0.89803922, 0.79607843],
        ...,
        [0.31372549, 0.31764706, 0.3254902 , ..., 0.36470588,
         0.3372549 , 0.3372549 ],
        [0.3

In [3]:
y_train[-3:]

array([[1],
       [0],
       [0]])

In [4]:
model = Sequential()

model.add(Flatten(input_shape=(50,50)))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(64, activation='relu'))


model.add(Dense(1, activation='sigmoid'))

model.compile(loss="binary_crossentropy",
             optimizer="adam",
             metrics=['accuracy'])

model.fit(X_train, y_train, validation_split=0.1, epochs=10)

Train on 22442 samples, validate on 2494 samples
Epoch 1/10
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
22442/22442 [==============================] - 3s 120us/sample - loss: 0.6957 - accuracy: 0.5333 - val_loss: 0.6792 - val_accuracy: 0.5822
Epoch 2/10
22442/22442 [==============================] - 2s 92us/sample - loss: 0.6796 - accuracy: 0.5631 - val_loss: 0.6687 - val_accuracy: 0.5866
Epoch 3/10
22442/22442 [==============================] - 2s 91us/sample - loss: 0.6712 - accuracy: 0.5778 - val_loss: 0.6638 - val_accuracy: 0.6022
Epoch 4/10
22442/22442 [==============================] - 2s 90us/sample - loss: 0.6698 - accuracy: 0.5875 - val_loss: 0.6627 - val_accuracy: 0.6115
Epoch 5/10
22442/22442 [==============================] - 2s 91us/sample - loss: 0.6668 - accuracy: 0.5911 - val_loss: 0.6608 - val_accuracy: 0.6099
Epoch 6/10
22442/22442 [==============================] - 2s 92us/sample - loss: 0.6657 - accuracy: 0.5935 - va

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 2500)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               320128    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 328,449
Trainable params: 328,449
Non-trainable params: 0
_________________________________________________________________


In [6]:
X = pickle.load(open("X.pickle","rb"))

X = np.array(X).reshape(-1,50,50)
X = X/255.0

In [7]:
hasil = model.predict([X[-10:]])
hasil[hasil<=0.5]=0
hasil[hasil>0.5]=1
hasil

array([[0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.]], dtype=float32)

In [8]:
y[-10:]

[0, 1, 0, 1, 0, 0, 0, 1, 0, 1]

In [15]:
model.save('my_model.h5')